# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_MODERATEUR: ROLE_USER
        ROLE_ADMIN:      [ROLE_USER, ROLE_MODERATEUR]

    encoders:
        EhsBundle\Entity\Users:
            algorithm: bcrypt
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: EhsBundle:Users
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: users_login
                check_path: users_login
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
        
            logout:
                path: users_logout
                target: users_login

    access_control:
        # - { path: ^/users/new, role: ROLE_ADMIN }
        - { path: ^/users/show, role: ROLE_ADMIN }
        - { path: ^/articles/new, role: ROLE_USER }
        - { path: ^/articles/[0-9]+/edit, role: ROLE_MODERATEUR }
        - { path: ^/articles/[0-9]+/publish, role: ROLE_ADMIN }
        - { path: ^/articles/[0-9]+/refused, role: ROLE_ADMIN }
        - { path: ^/comment/new, role: ROLE_USER }
        - { path: ^/comment/[0-9]+/edit, role: ROLE_MODERATEUR }
        - { path: ^/newsletter, role: ROLE_ADMIN }
        - { path: ^/presentation/[0-9]+/edit, role: ROLE_ADMIN }
        - { path: ^/presentation/new, role: ROLE_ADMIN }
        - { path: ^/agenda/[0-9]+/edit, role: ROLE_ADMIN }
        - { path: ^/agenda/new, role: ROLE_ADMIN }

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html