<?php

namespace EhsBundle\Repository;

/**
 * AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEvent(){
        return $this
			->createQueryBuilder('e')
			->where('e.startingDate > :now')
			->orderBy('e.startingDate', 'ASC')
            ->setParameter('now', new \DateTime('now'))
            ->setMaxResults(3)
			->getQuery()
			->getResult()
			;
    }
}
