<?php

namespace EhsBundle\Repository;

/**
 * ImagesCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagesCollectionRepository extends \Doctrine\ORM\EntityRepository
{
}
