<?php

namespace EhsBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{

	/**
	 * nbr of images displayable
	 */
	public function countAll()
	{
	    return $this
			->createQueryBuilder('i')
			->select('count(i.id)')
			->getQuery()
			->getSingleScalarResult()
			;
	}
}
