<?php

namespace EhsBundle\Repository;

/**
 * UsersAgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersAgendaRepository extends \Doctrine\ORM\EntityRepository
{
}
