articles_index:
    path:     /
    defaults: { _controller: "EhsBundle:Articles:index" }
    methods:  GET

articles_show:
    path:     /{id}/show
    defaults: { _controller: "EhsBundle:Articles:show" }
    methods:  [GET, POST]

articles_new:
    path:     /new
    defaults: { _controller: "EhsBundle:Articles:new" }
    methods:  [GET, POST]

articles_edit:
    path:     /{id}/edit
    defaults: { _controller: "EhsBundle:Articles:edit" }
    methods:  [GET, POST]

articles_delete:
    path:     /{id}/delete
    defaults: { _controller: "EhsBundle:Articles:delete" }
    methods:  DELETE

#articles_page:
#    path:     /page/{nbr}
#    defaults: { _controller: "EhsBundle:Articles:page" }
#    methods:  [GET, POST]


#articles_tag:
#    path:     /page/{nbr}/{tag}
#    defaults: { _controller: "EhsBundle:Articles:tag" }
#    methods:  [GET, POST]