image_index:
    path:     /
    defaults: { _controller: "EhsBundle:Image:index" }
    methods:  GET

image_show:
    path:     /{id}/show
    defaults: { _controller: "EhsBundle:Image:show" }
    methods:  GET

image_delete:
    path:     /{id}/delete
    defaults: { _controller: "EhsBundle:Image:delete" }
    methods:  DELETE

image_page:
    path:     /page/{nbr}
    defaults: { _controller: "EhsBundle:Image:page" }
    methods:  [GET, POST]
