newsletter_index:
    path:     /
    defaults: { _controller: "EhsBundle:Newsletter:index" }
    methods:  GET

newsletter_edit:
    path:     /{id}/edit
    defaults: { _controller: "EhsBundle:Newsletter:edit" }
    methods:  [GET, POST]
