question_index:
    path:     /
    defaults: { _controller: "EhsBundle:Question:index" }
    methods:  GET

question_show:
    path:     /{id}/show
    defaults: { _controller: "EhsBundle:Question:show" }
    methods:  GET

question_new:
    path:     /new
    defaults: { _controller: "EhsBundle:Question:new" }
    methods:  [GET, POST]

question_edit:
    path:     /{id}/edit
    defaults: { _controller: "EhsBundle:Question:edit" }
    methods:  [GET, POST]

question_delete:
    path:     /{id}/delete
    defaults: { _controller: "EhsBundle:Question:delete" }
    methods:  DELETE
