users_index:
    path:     /
    defaults: { _controller: "EhsBundle:Users:index" }
    methods:  GET

users_show:
    path:     /{id}/show
    defaults: { _controller: "EhsBundle:Users:show" }
    methods:  GET

users_show_profil:
    path:     /{id}/showProfil
    defaults: { _controller: "EhsBundle:Users:showProfil" }
    methods:  GET

users_new:
    path:     /new
    defaults: { _controller: "EhsBundle:Users:new" }
    methods:  [GET, POST]

users_edit:
    path:     /{id}/edit
    defaults: { _controller: "EhsBundle:Users:edit" }
    methods:  [GET, POST]

users_delete:
    path:     /{id}/delete
    defaults: { _controller: "EhsBundle:Users:delete" }
    methods:  DELETE

users_login:
    path:     /login
    defaults: { _controller: "EhsBundle:Security:login" }

users_logout:
    path:     /logout
    defaults: { _controller: "EhsBundle:Security:logout" }

users_passwordLost:
    path:     /passwordLost
    defaults: { _controller: "EhsBundle:Users:reset" }

users_passwordLostConfirm:
    path:     /passwordLostConfirm
    defaults: { _controller: "EhsBundle:Users:resetNow" }