ehs_users:
   resource: "@EhsBundle/Resources/config/routing/users.yml"
   prefix:   /users

ehs_articles:
    resource: "@EhsBundle/Resources/config/routing/articles.yml"
    prefix:   /articles

ehs_homepage:
    path:     /
    defaults: { _controller: EhsBundle:Default:index }

ehs_newsletter:
    resource: "@EhsBundle/Resources/config/routing/newsletter.yml"
    prefix:   /newsletter

ehs_comment:
    resource: "@EhsBundle/Resources/config/routing/comment.yml"
    prefix:   /comment
