ehs_users:
   resource: "@EhsBundle/Resources/config/routing/users.yml"
   prefix:   /users

ehs_articles:
    resource: "@EhsBundle/Resources/config/routing/articles.yml"
    prefix:   /articles

ehs_homepage:
    path:     /
    defaults: { _controller: EhsBundle:Default:index }

ehs_newsletter:
    resource: "@EhsBundle/Resources/config/routing/newsletter.yml"
    prefix:   /newsletter

ehs_comment:
    resource: "@EhsBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

ehs_admin:
    resource: "@EhsBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

ehs_contact:
    resource: "@EhsBundle/Resources/config/routing/contact.yml"
    prefix:   /contact

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"

ehs_presentation:
    resource: "@EhsBundle/Resources/config/routing/presentation.yml"
    prefix:   /presentation

ehs_agenda:
    resource: "@EhsBundle/Resources/config/routing/agenda.yml"
    prefix:   /agenda
