ehs_users:
   resource: "@EhsBundle/Resources/config/routing/users.yml"
   prefix:   /users
   
ehs_articles:
    resource: "@EhsBundle/Resources/config/routing/articles.yml"
    prefix:   /articles

ehs_homepage:
    path:     /
    defaults: { _controller: EhsBundle:Default:index }

